nasbench-101:
  channels: 16
  dataset: cifar10
  nodes: 5
  epochs: 60
  batch_size: 512
  nas_bench_dir: /data/Fanliang/data/
  n_samples: 200
  total_eval: 150
  pop_size: 20
  p_c: 0.5
  p_m: 0.05


nasbench-201:
  channels: 16
  dataset: ImageNet16-120
  nodes: 5
  epochs: 60
  batch_size: 512
  n_samples: 200
  pop_size: 20
  nas_bench_dir: /data/Fanliang/data/
  total_eval: 100
  p_c: 0.5
  p_m: 0.05


nasbench-301:
    channels: 32
    dataset: cifar10
    nodes: 4
    epochs: 150
    batch_size: 256
    pop_size: 30
    nas_bench_dir: 