nasbench-201:
  channels: 16
  dataset: cifar10
  nodes: 5
  epochs: 60
  batch_size: 512
  n_samples: 200
  pop_size: 20
  nas_bench_dir: /data/Fanliang/data/

nasbench-301:
    channels: 32
    dataset: cifar10
    nodes: 4
    epochs: 150
    batch_size: 256
    pop_size: 30